RFC-0002: Attribute ordering overlay
the-human-colossus-foundation/oca-spec pull request #24
Opened 2023-09-27 13:37 UTC by ryanbnl

2023-09-28 18:30 UTC, mitfik requested changes

2023-09-28 18:30 UTC, mitfik commented on .gitignore
> +.DS_Store
not related to RFC, should be removed.

2023-09-28 18:51 UTC, ryanbnl commented on .gitignore
> +.DS_Store
Sure, if you can update the ignores such that this Apple shit (and any other super common OS noise) in another PR it'd be awesome!

2023-10-05 07:09 UTC, ryanbnl commented
Moved the .gitignore changes to #25 and extended them.

2023-10-05 08:04 UTC, merged